In [1]:
# Email spam and not spam detection

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [34]:
df=pd.read_csv("emails.csv")
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [35]:
df.shape

(5172, 3002)

In [36]:
df.info

<bound method DataFrame.info of        Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrast

In [37]:
df.describe()

the           to          ect          and          for  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000   
mean      6.640565     6.188128     5.143852     3.075599     3.124710   
std      11.745009     9.534576    14.101142     6.045970     4.680522   
min       0.000000     0.000000     1.000000     0.000000     0.000000   
25%       0.000000     1.000000     1.000000     0.000000     1.000000   
50%       3.000000     3.000000     1.000000     1.000000     2.000000   
75%       8.000000     7.000000     4.000000     3.000000     4.000000   
max     210.000000   132.000000   344.000000    89.000000    47.000000   

                of            a          you          hou           in  ...  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  ...   
mean      2.627030    55.517401     2.466551     2.024362    10.600155  ...   
std       6.229845    87.574172     4.314444     6.967878    19.281892  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000    12.000000     0.000000     0.000000     1.000000  ...   
50%       1.000000    28.000000     1.000000     0.000000     5.000000  ...   
75%       2.000000    62.250000     3.000000     1.000000    12.000000  ...   
max      77.000000  1898.000000    70.000000   167.000000   223.000000  ...   

          connevey          jay       valued          lay  infrastructure  \
count  5172.000000  5172.000000  5172.000000  5172.000000     5172.000000   
mean      0.005027     0.012568     0.010634     0.098028        0.004254   
std       0.105788     0.199682     0.116693     0.569532        0.096252   
min       0.000000     0.000000     0.000000     0.000000        0.000000   
25%       0.000000     0.000000     0.000000     0.000000        0.000000   
50%       0.000000     0.000000     0.000000     0.000000        0.000000   
75%       0.000000     0.000000     0.000000     0.000000        0.000000   
max       4.000000     7.000000     2.000000    12.000000        3.000000   

          military     allowing           ff          dry   Prediction  
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  
mean      0.006574     0.004060     0.914733     0.006961     0.290023  
std       0.138908     0.072145     2.780203     0.098086     0.453817  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     1.000000     0.000000     1.000000  
max       4.000000     3.000000   114.000000     4.000000     1.000000  

[8 rows x 3001 columns]

In [38]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [39]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [45]:
df.drop(['Email No.'],axis=1, inplace=True)

In [49]:
# In X and Y variables
X=df.drop(['Prediction'],axis=1)
y=df['Prediction']

In [98]:
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split
X=scale(X)
X_train,X_test,y_train,y_test1=train_test_split(X,y,test_size=0.2, random_state=42)
X_train,X_test,y_train,y_test1

(array([[-0.05454457, -0.22951624, -0.2229717 , ..., -0.0562853 ,
          0.03067224, -0.07097072],
        [-0.56544926, -0.64908256, -0.2938948 , ..., -0.0562853 ,
         -0.32904848, -0.07097072],
        [ 2.84058199,  2.28788165, -0.0811255 , ..., -0.0562853 ,
          0.75011369, -0.07097072],
        ...,
        [-0.56544926, -0.64908256, -0.2938948 , ..., -0.0562853 ,
         -0.32904848, -0.07097072],
        [-0.3951477 ,  0.50472481, -0.2938948 , ..., -0.0562853 ,
          0.75011369, -0.07097072],
        [-0.30999692, -0.64908256, -0.2938948 , ..., -0.0562853 ,
         -0.32904848, -0.07097072]]),
 array([[-0.48029848, -0.54419098, -0.2938948 , ..., -0.0562853 ,
         -0.32904848, -0.07097072],
        [ 0.5415109 ,  1.44874902,  4.31610679, ..., -0.0562853 ,
         -0.32904848, -0.07097072],
        [-0.48029848,  0.81939955, -0.1520486 , ..., -0.0562853 ,
          1.46955514, -0.07097072],
        ...,
        [-0.56544926, -0.64908256, -0.2938948 , ..., -

In [99]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [102]:
knn=KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train,y_train)
y_pred1=knn.predict(X_test)

In [104]:
print("Prediction",y_pred1)

Prediction [0 0 1 ... 0 1 0]


In [106]:
# Evaluation
print("Accuracy: ",metrics.accuracy_score(y_test1,y_pred1))
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test1,y_pred1))

Accuracy:  0.8444444444444444
Confusion Matrix: 
 [[599 140]
 [ 21 275]]


In [108]:
knn_accuracy=metrics.accuracy_score(y_test1,y_pred1)

In [110]:
from sklearn.svm import SVC
svc=SVC(C=1)
svc.fit(X_train,y_train)

SVC(C=1)

In [111]:
y_pred=svc.predict(X_test)

In [112]:
print("Accuracy: ",metrics.accuracy_score(y_test,y_pred))
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test,y_pred))

Accuracy:  0.9468599033816425
Confusion Matrix: 
 [[738   1]
 [ 54 242]]


In [113]:
svm_accuracy=metrics.accuracy_score(y_test,y_pred)

In [114]:
results = pd.DataFrame({
    'Model': ['K-Nearest Neighbors', 'Support Vector Machine'],
    'Accuracy': [knn_accuracy, svm_accuracy]
})

print("\nModel Comparison:\n", results)


Model Comparison:
                     Model  Accuracy
0     K-Nearest Neighbors  0.844444
1  Support Vector Machine  0.946860
